GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU

###title
GET http://localhost:3000/tasks?title=task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###title doesnt exist
GET http://localhost:3000/tasks?title=run
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###priority
GET http://localhost:3000/tasks?priority=medium
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU

###priority doesnt exist
GET http://localhost:3000/tasks?priority=high
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###priority invalid
GET http://localhost:3000/tasks?priority=mediummm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###status
GET http://localhost:3000/tasks?status=toDo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###status doesnt exist
GET http://localhost:3000/tasks?status=done
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###status invalid
GET http://localhost:3000/tasks?status=jjj
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###status,priority ,title
GET http://localhost:3000/tasks?status=toDo&&priority=medium&&title=tas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###ssortby due
GET http://localhost:3000/tasks?sort_by=createdAt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###ssortby due
GET http://localhost:3000/tasks?sort_by=dueDate&&order=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
###ssortby due,search
GET http://localhost:3000/tasks?sort_by=dueDate&&order=desc&&title=dtas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5Mzc5MSwiZXhwIjoxNzUzNzk1NTkxfQ.0MujHhjY_gEaGNLWNxaADNA9NCKyqetd2mUImsW-ywU
####
GET http://localhost:3000/tasks?sort_by=dueDate&&order=desc&&title=t
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5NTY4NywiZXhwIjoxNzUzNzk3NDg3fQ.ok_e4G0TIbgx7fTOyd6VxbifYuClSuGxoKgKoobAV0s
####t
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6InRAZ21haWwuY29tIiwibmFtZSI6InQiLCJpYXQiOjE3NTM3OTcxOTMsImV4cCI6MTc1Mzc5ODk5M30.geiGANLhtbMh3pUyywUeCDKFERX7gjQurZGjJhLBhGg

###toqua
GET http://localhost:3000/tasks?title=atas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1Mzc5NzMwMywiZXhwIjoxNzUzNzk5MTAzfQ.c9tJEDH_OzTlUPPSYBBYnyvWmmcWEPETMeBqIQ4TAK0