DELETE http://localhost:3000/tasks/k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDM1NTE4OCwiZXhwIjoxNzU0MzU2OTg4fQ.q8wFZ1tLlI8w9VPELqNZio40eUTHBK_-CC3nXj8uPaw