DELETE http://localhost:3000/tasks/k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDQzOTkyNiwiZXhwIjoxNzU0NDQxNzI2fQ.c-5jgKA6K6_JnwHbPeRbcBamcEwV_kRyByWRdt5SiIU
