GET http://localhost:3000/tasks 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDM1OTEzNSwiZXhwIjoxNzU0MzYwOTM1fQ.1O-MgjRuENovTylaZLPa-e62RNICNtZKqPmjtxjK2S0
###
GET http://localhost:3000/tasks?title=Task&&limit_by=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDAwMTUxNCwiZXhwIjoxNzU0MDAzMzE0fQ.aUMG1wb8mr2cDufpMO_-LddyIzIucnELogPJUzIKjDA
###
GET http://localhost:3000/tasks?title=Task&&limit_by=7&&page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDAwMTUxNCwiZXhwIjoxNzU0MDAzMzE0fQ.aUMG1wb8mr2cDufpMO_-LddyIzIucnELogPJUzIKjDA
###
GET  http://localhost:3000/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRvcXVhQGdtYWlsLmNvbSIsIm5hbWUiOiJ0b3F1YSIsImlhdCI6MTc1NDM1OTEzNSwiZXhwIjoxNzU0MzYwOTM1fQ.1O-MgjRuENovTylaZLPa-e62RNICNtZKqPmjtxjK2S0
